name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Optional: Set the region from secrets

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1  # Login to AWS ECR
      with:
        region: ${{ secrets.AWS_REGION }}  # Set your AWS region (e.g., ap-northeast-2)

    - name: Build Docker image
      run: |
        docker build -t my-app .  # Build Docker image with the tag 'my-app'

    - name: Tag Docker image
      run: |
        docker tag my-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-repository:latest  # Tag with ECR repository URI

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interview/introduction:latest  # Push the tagged image to ECR
